# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'userNameAndPassWord' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'
  # Pods for userNameAndPassWord

  target 'userNameAndPassWordTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'userNameAndPassWordUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
